### ISSUE TITLE
Move World Geographical Scheme for Recording Plant Distributions out of prior standards?

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/prior-standards#19]
See #18: there is interest to update this standard. If a maintainer can be found, it might make sense to move this standard out of this repository and give it its own repository, where it can be maintained and downloaded?
- [x] Find maintainer
- [x] Create team
- [x] Move content to new repo
- [x] Update URL redirect

**Comment by peterdesmet** [comment]
* Repo created at https://github.com/tdwg/wgsrpd
* Team called WGSRPD
* I'm currently maintainer with @mdoering. 
* Redirect updated at https://github.com/tdwg/infrastructure/commit/145d5b7c0126ad6c64bb08111d7e9f67c3ac6d24

@mdoering does anything need to happen to make that redirect work?

**Comment by pmergen** [comment]
Hi 
you can fine a current application of the standard here : https://dev.e-taxonomy.eu/redmine/projects/edit/wiki/MapRestServiceExamples
The shape files are updated regularly here and can be access/downloaded freely : http://edit.africamuseum.be/geoserver/web/?wicket:bookmarkablePage=:org.geoserver.web.demo.MapPreviewPage
You can find there also the explanation on how to use them in Rest Services and other applications to display them in websites, portals or produce maps for different purposes. 
It is currently maintained jointly by BGBM Berlin and the Royal Museum for Central Africa  here : https://cybertaxonomy.eu/

A first question to resolve and agree is if the above application of the standard is to be part of the TDWG standard or seen just as an application of the standard, notably updating the shape files. 

Probably clarifying this and which is in scope of TDWG and which not, will also help to have a maintainer come forward, because maintaining a full geo-server where you can download layers with a service to update them is much more a commitment, then maintaining the standard on how to provide them in a standard way is another story. 
Pat

**Comment by mdoering** [comment]
Thanks @pmergen, let's move all specific discussions to the new repository.
E.g. here: https://github.com/tdwg/wgsrpd/issues/3
